### PR TITLE
fix #70 : added and refactored toasts on login/signup

### LINKED ISSUE #70: [BUG]: Implement Error Handling in login/signup forms
### Describe the bug

When I was testing the login and signup functionalities, I came across a situation when I was hitting the signup button and nothing is happening. I opened the console to find out the problem, it was just an error saying that I have already used this account to login. Also user has no way of knowing if an error occurs during a login.

### Steps To Reproduce

For Signup error: Make a google login with an account, try to signup using the same account.
edit: sign up using credentials with same account
For login error: Signup through credentials and type incorrect password in login.

### Expected Behavior

I expect a toast or banner or some other way of showing the user that "this" is the problem to abort the login/signup. Since regular users don't have the habit of opening consoles for errors.

Elaborate your implementation approach when requesting for assignment.

### Screenshots/Videos

_No response_

### What device are you using?

_No response_

### Operating System

_No response_

### What browsers are you seeing the problem on?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Om-Thorat**
## Overview

1. This PR fixes or fixes part of #70 .
2. This PR does the following: Added Error toasts on signups and login, also refactored and made a usetoast.js file making easier to show toasts in future on other places and cleaner code.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/BSoC-Website/assets/76207818/9965ea37-7c00-4604-aff0-f53784776172

## PR Pointers

- The number of + - might be high because of the new formatting on commit, The files for some reason weren't previously formatted.

### CODE REVIEW

File: src/views/Auth.vue [hunk 1]
```diff
@@ -1,35 +1,34 @@
...
+import { useRouter } from 'vue-router'
+import ToastComponent from '../components/ToastComponent.vue'
 
 export default {
-  name: "Auth",
-  components: {Signup, Login},
-  setup() {
-    const toggle = ref(true);
+	name: 'Auth',
+	components: { Signup, Login, ToastComponent },
```
Comment (ramG-reddy) [inline src/views/Auth.vue:15]: Remove the import here, as you were doing it in App.vue

Comment (Om-Thorat) [reply src/views/Auth.vue]: done!

Comment (Om-Thorat) [reply src/views/Auth.vue]: done!
